In [1]:
from utils.config import load_config
from analysis.target_analysis import analyze_numeric_feature
from analysis.numeric.numeric_summary import build_numeric_summary
from feature_utils.feature_engineering import replace_with_has_large
from feature_utils.data_cleaning import fill_missing_values
import pandas as pd
%matplotlib inline

In [2]:
config = load_config()
train_df = pd.read_csv(config["paths"]["train"])
train_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
summary = build_numeric_summary(train_df)
summary

,feature,mean,median,std,min,max,missing,missing_%,has_outliers,skew
2,LotFrontage,70.049958,69.0,24.284752,21.0,313.0,True,0.177397,True,2.163569
25,GarageYrBlt,1978.506164,1980.0,24.689725,1900.0,2010.0,True,0.055479,False,-0.649415
8,MasVnrArea,103.685262,0.0,181.066207,0.0,1600.0,True,0.005479,True,2.669084
3,LotArea,10516.828082,9478.5,9981.264932,1300.0,215245.0,False,0.000000,True,12.207688
1,MSSubClass,56.897260,50.0,42.300571,20.0,190.0,False,0.000000,True,1.407657
0,Id,730.500000,730.5,421.610009,1.0,1460.0,False,0.000000,False,0.000000
5,OverallCond,5.575342,5.0,1.112799,1.0,9.0,False,0.000000,True,0.693067
4,OverallQual,6.099315,6.0,1.382997,1.0,10.0,False,0.000000,True,0.216944
7,YearRemodAdd,1984.865753,1994.0,20.645407,1950.0,2010.0,False,0.000000,False,-0.503562
6,YearBuilt,1971.267808,1973.0,30.202904,1872.0,2010.0,False,0.000000,True,-0.613461
10,BsmtFinSF2,46.549315,0.0,161.319273,0.0,1474.0,False,0.000000,True,4.255261
11,BsmtUnfSF,567.240411,477.5,441.866955,0.0,2336.0,False,0.000000,True,0.920268
12,TotalBsmtSF,1057.429452,991.5,438.705324,0.0,6110.0,False,0.000000,True,1.524255
9,BsmtFinSF1,443.639726,383.5,456.098091,0.0,5644.0,False,0.000000,True,1.685503
14,2ndFlrSF,346.992466,0.0,436.528436,0.0,2065.0,False,0.000000,True,0.813030
15,LowQualFinSF,5.844521,0.0,48.623081,0.0,572.0,False,0.000000,True,9.011341
16,GrLivArea,1515.463699,1464.0,525.480383,334.0,5642.0,False,0.000000,True,1.366560
17,BsmtFullBath,0.425342,0.0,0.518911,0.0,3.0,False,0.000000,True,0.596067
18,BsmtHalfBath,0.057534,0.0,0.238753,0.0,2.0,False,0.000000,True,4.103403
19,FullBath,1.565068,2.0,0.550916,0.0,3.0,False,0.000000,False,0.036562
20,HalfBath,0.382877,0.0,0.502885,0.0,2.0,False,0.000000,False,0.675897
13,1stFlrSF,1162.626712,1087.0,386.587738,334.0,4692.0,False,0.000000,True,1.376757
21,BedroomAbvGr,2.866438,3.0,0.815778,0.0,8.0,False,0.000000,True,0.211790
22,KitchenAbvGr,1.046575,1.0,0.220338,0.0,3.0,False,0.000000,True,4.488397
23,TotRmsAbvGrd,6.517808,6.0,1.625393,2.0,14.0,False,0.000000,True,0.676341
24,Fireplaces,0.613014,1.0,0.644666,0.0,3.0,False,0.000000,True,0.649565
26,GarageCars,1.767123,2.0,0.747315,0.0,4.0,False,0.000000,True,-0.342549
27,GarageArea,472.980137,480.0,213.804841,0.0,1418.0,False,0.000000,True,0.179981
28,WoodDeckSF,94.244521,0.0,125.338794,0.0,857.0,False,0.000000,True,1.541376
29,OpenPorchSF,46.660274,25.0,66.256028,0.0,547.0,False,0.000000,True,2.364342
30,EnclosedPorch,21.954110,0.0,61.119149,0.0,552.0,False,0.000000,True,3.089872
31,3SsnPorch,3.409589,0.0,29.317331,0.0,508.0,False,0.000000,True,10.304342
32,ScreenPorch,15.060959,0.0,55.757415,0.0,480.0,False,0.000000,True,4.122214
33,PoolArea,2.758904,0.0,40.177307,0.0,738.0,False,0.000000,True,14.828374
34,MiscVal,43.489041,0.0,496.123024,0.0,15500.0,False,0.000000,True,24.476794
35,MoSold,6.321918,6.0,2.703626,1.0,12.0,False,0.000000,False,0.212053
36,YrSold,2007.815753,2008.0,1.328095,2006.0,2010.0,False,0.000000,False,0.096269
37,SalePrice,180921.195890,163000.0,79442.502883,34900.0,755000.0,False,0.000000,True,1.882876

## Feature Engineering: sparse numerical features

В процессе анализа числовых признаков было обнаружено, что некоторые из них имеют сильный перекос распределения (high skew) и медиану, равную 0.

Это означает:
- большинство значений в этих признаках равно 0
- небольшое количество объектов имеет ненулевые (иногда большие) значения

К таким признакам относятся:
- `MiscVal`
- `PoolArea`
- `3SsnPorch`
- `LowQualFinSF`

### Интерпретация

Для данных признаков более важен **факт наличия**, чем конкретное значение.

Например:
- наличие бассейна (`PoolArea > 0`) важнее его площади
- наличие дополнительных построек (`MiscVal > 0`) важнее их стоимости

### Принятое решение

Преобразовать данные признаки в бинарный формат:
- `1` — признак присутствует
- `0` — отсутствует

### Причины такого подхода

- уменьшение влияния выбросов
- упрощение модели
- повышение устойчивости к шуму
- улучшение интерпретируемости

### Результат

Каждый признак заменяется на новый бинарный:
- `Has_MiscVal`
- `Has_PoolArea`
- `Has_3SsnPorch`
- `Has_LowQualFinSF`

Оригинальные признаки удаляются из датасета.

In [4]:
features_sparse = [
    'MiscVal',
    'PoolArea',
    '3SsnPorch',
    'LowQualFinSF'
]

train_df = replace_with_has_large(train_df, features_sparse)

In [5]:
summary = build_numeric_summary(train_df)
summary

,feature,mean,median,std,min,max,missing,missing_%,has_outliers,skew
2,LotFrontage,70.049958,69.0,24.284752,21.0,313.0,True,0.177397,True,2.163569
24,GarageYrBlt,1978.506164,1980.0,24.689725,1900.0,2010.0,True,0.055479,False,-0.649415
8,MasVnrArea,103.685262,0.0,181.066207,0.0,1600.0,True,0.005479,True,2.669084
3,LotArea,10516.828082,9478.5,9981.264932,1300.0,215245.0,False,0.000000,True,12.207688
1,MSSubClass,56.897260,50.0,42.300571,20.0,190.0,False,0.000000,True,1.407657
0,Id,730.500000,730.5,421.610009,1.0,1460.0,False,0.000000,False,0.000000
5,OverallCond,5.575342,5.0,1.112799,1.0,9.0,False,0.000000,True,0.693067
4,OverallQual,6.099315,6.0,1.382997,1.0,10.0,False,0.000000,True,0.216944
7,YearRemodAdd,1984.865753,1994.0,20.645407,1950.0,2010.0,False,0.000000,False,-0.503562
6,YearBuilt,1971.267808,1973.0,30.202904,1872.0,2010.0,False,0.000000,True,-0.613461
10,BsmtFinSF2,46.549315,0.0,161.319273,0.0,1474.0,False,0.000000,True,4.255261
11,BsmtUnfSF,567.240411,477.5,441.866955,0.0,2336.0,False,0.000000,True,0.920268
12,TotalBsmtSF,1057.429452,991.5,438.705324,0.0,6110.0,False,0.000000,True,1.524255
9,BsmtFinSF1,443.639726,383.5,456.098091,0.0,5644.0,False,0.000000,True,1.685503
14,2ndFlrSF,346.992466,0.0,436.528436,0.0,2065.0,False,0.000000,True,0.813030
15,GrLivArea,1515.463699,1464.0,525.480383,334.0,5642.0,False,0.000000,True,1.366560
16,BsmtFullBath,0.425342,0.0,0.518911,0.0,3.0,False,0.000000,True,0.596067
17,BsmtHalfBath,0.057534,0.0,0.238753,0.0,2.0,False,0.000000,True,4.103403
18,FullBath,1.565068,2.0,0.550916,0.0,3.0,False,0.000000,False,0.036562
19,HalfBath,0.382877,0.0,0.502885,0.0,2.0,False,0.000000,False,0.675897
20,BedroomAbvGr,2.866438,3.0,0.815778,0.0,8.0,False,0.000000,True,0.211790
13,1stFlrSF,1162.626712,1087.0,386.587738,334.0,4692.0,False,0.000000,True,1.376757
21,KitchenAbvGr,1.046575,1.0,0.220338,0.0,3.0,False,0.000000,True,4.488397
22,TotRmsAbvGrd,6.517808,6.0,1.625393,2.0,14.0,False,0.000000,True,0.676341
23,Fireplaces,0.613014,1.0,0.644666,0.0,3.0,False,0.000000,True,0.649565
25,GarageCars,1.767123,2.0,0.747315,0.0,4.0,False,0.000000,True,-0.342549
26,GarageArea,472.980137,480.0,213.804841,0.0,1418.0,False,0.000000,True,0.179981
27,WoodDeckSF,94.244521,0.0,125.338794,0.0,857.0,False,0.000000,True,1.541376
28,OpenPorchSF,46.660274,25.0,66.256028,0.0,547.0,False,0.000000,True,2.364342
29,EnclosedPorch,21.954110,0.0,61.119149,0.0,552.0,False,0.000000,True,3.089872
30,ScreenPorch,15.060959,0.0,55.757415,0.0,480.0,False,0.000000,True,4.122214
31,MoSold,6.321918,6.0,2.703626,1.0,12.0,False,0.000000,False,0.212053
32,YrSold,2007.815753,2008.0,1.328095,2006.0,2010.0,False,0.000000,False,0.096269
33,SalePrice,180921.195890,163000.0,79442.502883,34900.0,755000.0,False,0.000000,True,1.882876
34,HasLarge_MiscVal,0.035616,0.0,0.185395,0.0,1.0,False,0.000000,True,5.016528
35,HasLarge_PoolArea,0.004795,0.0,0.069100,0.0,1.0,False,0.000000,True,14.352680
36,HasLarge_3SsnPorch,0.016438,0.0,0.127198,0.0,1.0,False,0.000000,True,7.613746
37,HasLarge_LowQualFinSF,0.017808,0.0,0.132299,0.0,1.0,False,0.000000,True,7.299413

# Обработка пропусков (Missing Values)

## 📊 Анализ данных

В ходе EDA были найдены признаки с пропусками:

| Feature        | Missing % | Skew   | Outliers |
|---------------|----------|--------|----------|
| LotFrontage   | 17.7%    | 2.16   | ✅       |
| GarageYrBlt   | 5.5%     | -0.64  | ❌       |
| MasVnrArea    | 0.5%     | 2.66   | ✅       |

---

## 🧠 Подход к заполнению

При выборе стратегии использовались следующие правила:

1. Если распределение **смещено (skew > 1)** → используем **median**
2. Если распределение близко к нормальному → можно использовать **mean**
3. Если есть **выбросы** → median предпочтительнее
4. Если признак имеет **смысловую интерпретацию (например, 0 = отсутствие)** → важно учитывать это

In [7]:
df = fill_missing_values(
    train_df,
    columns=["LotFrontage", "GarageYrBlt", "MasVnrArea"],
    strategy="median",
)

In [8]:
summary = build_numeric_summary(train_df)
summary

,feature,mean,median,std,min,max,missing,missing_%,has_outliers,skew
0,Id,730.500000,730.5,421.610009,1.0,1460.0,False,0.0,False,0.000000
1,MSSubClass,56.897260,50.0,42.300571,20.0,190.0,False,0.0,True,1.407657
2,LotFrontage,69.863699,69.0,22.027677,21.0,313.0,False,0.0,True,2.409147
3,LotArea,10516.828082,9478.5,9981.264932,1300.0,215245.0,False,0.0,True,12.207688
4,OverallQual,6.099315,6.0,1.382997,1.0,10.0,False,0.0,True,0.216944
5,OverallCond,5.575342,5.0,1.112799,1.0,9.0,False,0.0,True,0.693067
6,YearBuilt,1971.267808,1973.0,30.202904,1872.0,2010.0,False,0.0,True,-0.613461
7,YearRemodAdd,1984.865753,1994.0,20.645407,1950.0,2010.0,False,0.0,False,-0.503562
8,MasVnrArea,103.117123,0.0,180.731373,0.0,1600.0,False,0.0,True,2.677616
9,BsmtFinSF1,443.639726,383.5,456.098091,0.0,5644.0,False,0.0,True,1.685503
10,BsmtFinSF2,46.549315,0.0,161.319273,0.0,1474.0,False,0.0,True,4.255261
11,BsmtUnfSF,567.240411,477.5,441.866955,0.0,2336.0,False,0.0,True,0.920268
12,TotalBsmtSF,1057.429452,991.5,438.705324,0.0,6110.0,False,0.0,True,1.524255
13,1stFlrSF,1162.626712,1087.0,386.587738,334.0,4692.0,False,0.0,True,1.376757
14,2ndFlrSF,346.992466,0.0,436.528436,0.0,2065.0,False,0.0,True,0.813030
15,GrLivArea,1515.463699,1464.0,525.480383,334.0,5642.0,False,0.0,True,1.366560
16,BsmtFullBath,0.425342,0.0,0.518911,0.0,3.0,False,0.0,True,0.596067
17,BsmtHalfBath,0.057534,0.0,0.238753,0.0,2.0,False,0.0,True,4.103403
18,FullBath,1.565068,2.0,0.550916,0.0,3.0,False,0.0,False,0.036562
19,HalfBath,0.382877,0.0,0.502885,0.0,2.0,False,0.0,False,0.675897
20,BedroomAbvGr,2.866438,3.0,0.815778,0.0,8.0,False,0.0,True,0.211790
21,KitchenAbvGr,1.046575,1.0,0.220338,0.0,3.0,False,0.0,True,4.488397
22,TotRmsAbvGrd,6.517808,6.0,1.625393,2.0,14.0,False,0.0,True,0.676341
23,Fireplaces,0.613014,1.0,0.644666,0.0,3.0,False,0.0,True,0.649565
24,GarageYrBlt,1978.589041,1980.0,23.997022,1900.0,2010.0,False,0.0,True,-0.678333
25,GarageCars,1.767123,2.0,0.747315,0.0,4.0,False,0.0,True,-0.342549
26,GarageArea,472.980137,480.0,213.804841,0.0,1418.0,False,0.0,True,0.179981
27,WoodDeckSF,94.244521,0.0,125.338794,0.0,857.0,False,0.0,True,1.541376
28,OpenPorchSF,46.660274,25.0,66.256028,0.0,547.0,False,0.0,True,2.364342
29,EnclosedPorch,21.954110,0.0,61.119149,0.0,552.0,False,0.0,True,3.089872
30,ScreenPorch,15.060959,0.0,55.757415,0.0,480.0,False,0.0,True,4.122214
31,MoSold,6.321918,6.0,2.703626,1.0,12.0,False,0.0,False,0.212053
32,YrSold,2007.815753,2008.0,1.328095,2006.0,2010.0,False,0.0,False,0.096269
33,SalePrice,180921.195890,163000.0,79442.502883,34900.0,755000.0,False,0.0,True,1.882876
34,HasLarge_MiscVal,0.035616,0.0,0.185395,0.0,1.0,False,0.0,True,5.016528
35,HasLarge_PoolArea,0.004795,0.0,0.069100,0.0,1.0,False,0.0,True,14.352680
36,HasLarge_3SsnPorch,0.016438,0.0,0.127198,0.0,1.0,False,0.0,True,7.613746
37,HasLarge_LowQualFinSF,0.017808,0.0,0.132299,0.0,1.0,False,0.0,True,7.299413